theme: jekyll-theme-minimal
title: Summer Durrant
description: Collection Services Librarian
logo: https://media-exp1.licdn.com/dms/image/C5603AQG8dI8xzdp8rA/profile-displayphoto-shrink_200_200/0/1517787607798?e=1643846400&v=beta&t=es-rh-u8gEF7C0bKLHmcvIU3yZBWNDfZh_yR2GtTuDA
show_downloads: false
